"""Guarded agent-session lifecycle helpers."""

from app.services.agent_sessions.service import (
    CONFIGURED_AI_CAPABILITY,
    SESSION_TTL,
    STANDARD_WRITE_CAPABILITIES,
    AgentSessionError,
    InvalidSessionSecretHash,
    SessionAuthenticationError,
    SessionCapabilityError,
    SessionNotFound,
    SessionStateError,
    SessionVersionConflict,
    approve_session,
    authenticate_session,
    effective_session_status,
    expire_session_if_needed,
    hash_session_secret,
    heartbeat_session,
    mark_session_exited,
    register_session,
    require_capability,
    revoke_session,
    verify_session_secret,
)

__all__ = [
    "CONFIGURED_AI_CAPABILITY",
    "SESSION_TTL",
    "STANDARD_WRITE_CAPABILITIES",
    "AgentSessionError",
    "InvalidSessionSecretHash",
    "SessionAuthenticationError",
    "SessionCapabilityError",
    "SessionNotFound",
    "SessionStateError",
    "SessionVersionConflict",
    "approve_session",
    "authenticate_session",
    "effective_session_status",
    "expire_session_if_needed",
    "hash_session_secret",
    "heartbeat_session",
    "mark_session_exited",
    "register_session",
    "require_capability",
    "revoke_session",
    "verify_session_secret",
]
